#!/bin/bash
# Move into correct directory
DIR=backups

cd ~/fall2024-comp206
mkdir -p $DIR
cp -r assignments $DIR
cd $DIR

# Create back-up named after the date
DATE=$(date +'%Y-%m-%dT%H:%M:%S')
tar -czf assignments.tar.gz assignments

# Check status code
if [ $? -eq 0 ]; then
	mv assignments.tar.gz assignments-$DATE.tar.gz
	echo "Created backup: $DIR/assignments-$DATE.tar.gz"
fi
